name: Descent 3 Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # In forks - all pushes and pull requests
    # In main repo - only pushes and pull requests to the main branch
    if: ( github.repository != 'kevinbentley/Descent3' )
     || ( github.repository == 'kevinbentley/Descent3'
          && github.ref == 'refs/heads/main' )

    strategy:
      fail-fast: false

      matrix:
        os:
          - {runner: windows-latest, preset: win}
          - {runner: macos-latest, preset: mac}
          - {runner: linux-latest, preset: linux}
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Install macOS dependencies
      if: ${{ matrix.os.preset == 'mac' }}
      run: |
        # Install packages from Homebrew
        brew bundle install

    - name: Install Linux dependencies
      if: ${{ matrix.os.preset == 'linux' }}
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y --no-install-recommends \
          make cmake g++ libsdl1.2-dev libsdl-image1.2-dev \
          libaudio-dev libaa1-dev libdirectfb-dev \
          libncurses-dev \
          libxext6:i386  # for ./scripts/hogutils/hogUtils-i686 binary

    - name: Configure CMake
      run: cmake --preset ${{matrix.os.preset}} -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build_${{matrix.build_type}}
        path: ${{github.workspace}}/build/Descent3/${{matrix.build_type}}
